// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_superlike_post is a generated GoMock package.
package mock_superlike_post

import (
	model "reactionservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateSuperlikePost mocks base method.
func (m *MockService) CreateSuperlikePost(superlike *model.SuperlikePost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSuperlikePost", superlike)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSuperlikePost indicates an expected call of CreateSuperlikePost.
func (mr *MockServiceMockRecorder) CreateSuperlikePost(superlike interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSuperlikePost", reflect.TypeOf((*MockService)(nil).CreateSuperlikePost), superlike)
}
