// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_unsuperlike_post is a generated GoMock package.
package mock_unsuperlike_post

import (
	model "reactionservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteSuperlikePost mocks base method.
func (m *MockService) DeleteSuperlikePost(superlike *model.SuperlikePost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSuperlikePost", superlike)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSuperlikePost indicates an expected call of DeleteSuperlikePost.
func (mr *MockServiceMockRecorder) DeleteSuperlikePost(superlike interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuperlikePost", reflect.TypeOf((*MockService)(nil).DeleteSuperlikePost), superlike)
}
